### ISSUE TITLE
build failed on MacOS, version 12.0.1

### ISSUE THREAD

**Issue by SerendipityMatthew** [romellfudi/FudiNFC#5] opened 2021-12-20 12:32 UTC
Platform: Mac OS
version: 12.0.1 
reason: build failed

Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

> Task :app:processDebugManifest
/Users/matthew/Downloads/github/FudiNFC/app/src/main/AndroidManifest.xml:15:5-40:19 Warning:
        application@android:label was tagged at AndroidManifest.xml:15 to replace other declarations but no other declaration present

> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/matthew/.gradle/caches/transforms-2/files-2.1/222fb1e9b4241bd7b141674dfe2701ed/core-1.8.0-alpha02/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

the build failed, it's seem that you use the "+" for the version of androidx.core:core-ktx, it should be 1.6.0.

**Comment by romellfudi** [comment] 2021-12-22 05:03
Do you check your manifest, please @xuwanjin ?

**Comment by romellfudi** [comment] 2021-12-26 12:58
Hi @xuwanjin , Do you still have the same issues?

**Comment by romellfudi** [comment] 2021-12-30 16:02
I will close it due to non-answering

**Comment by SerendipityMatthew** [comment] 2022-04-13 11:00
sorry to forgot the issue (recently i am busy on my work). now I test on macos, git pull . gradle clean. then build (gradlew assembleDebug) , it's still failed. the solution is here: https://stackoverflow.com/questions/69033022/message-error-resource-androidattr-lstar-not-found

**Comment by romellfudi** [comment] 2022-04-14 01:06
@xuwanjin , please send the PR asap to merge it 

Send the steps to reproduce the issue.

_Sent from my Galaxy S8+ using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SerendipityMatthew** [comment] 2022-04-16 22:15
here is the pull request: https://github.com/romellfudi/FudiNFC/pull/9

**Closed as completed** 2022-04-17 15:42 UTC
Labels: invalid, question
